---
title: "Assignment 1"
author: "202005905"
date: "October 2023"
output: html_document
---

```{r setup, include=FALSE} 
# this chunk contains code that sets global options for the entire .Rmd. 
# we use include=FALSE to suppress it from the top of the document, but it will still appear in the appendix. 

knitr::opts_chunk$set(echo = FALSE) # actually set the global chunk options. 
# we set echo=FALSE to suppress code such that it by default does not appear throughout the document. 
# note: this is different from .Rmd default
```

### Exercise 1

Here, I will present the results of writing  for loop that prints out the numbers 1 to 10

```{r ex1}
for(i in 1:10) {
  print(i)
}

```

This prints the numbers 1 to 10, each on a seperate line.

```{r ex2}
for(i in 1:10) {
  print(i)
}

```

## Appendix: All code in this assignment

```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE} 
# this chunk generates the complete code appendix. 
# eval=FALSE tells R not to run (``evaluate'') the code here (it was already run before).
```
